variables:
  CONTAINER_REGISTRY: docker.io
  IMAGE_NAMESPACE: alikov

stages:
  - clean
  - build
  - manifest-list

.check-updates:
  tags:
    - podman
    - $ARCH
  stage: .pre
  variables:
    ENV_FILENAME: "check-updates-${FEDORA_VERSION}-${ARCH}.env"
  script:
    - ./dnf-update-flags.py --var-prefix "${ARCH}_" "${CONTAINER_REGISTRY}/${IMAGE_NAMESPACE%/}/fedora-base:${FEDORA_VERSION}" "$ENV_FILENAME"
    - cat "$ENV_FILENAME"
  artifacts:
    reports:
      dotenv: $ENV_FILENAME
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"

.build:
  tags:
    - podman
    - $ARCH
  stage: build
  variables:
    OUTPUT_METADATA_FILE: "ci/tmp/${FEDORA_VERSION}-${ARCH}.json"
  script:
    - ./ci/scripts/skip-build.sh || ./ci/scripts/build.sh
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - when: manual
      allow_failure: true
      variables:
        FORCE_BUILD: "1"
  artifacts:
    paths:
      - $OUTPUT_METADATA_FILE
    expire_in: 1 day

.make-manifest-list:
  stage: manifest-list
  tags:
    - podman
    - x86_64
  variables:
    AMD64_METADATA_FILE: "ci/tmp/${FEDORA_VERSION}-x86_64.json"
    ARM64_METADATA_FILE: "ci/tmp/${FEDORA_VERSION}-aarch64.json"
  script:
    - ./ci/scripts/skip-build.sh || ./ci/scripts/make-manifest-list.sh
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - when: manual
      allow_failure: true
      variables:
        FORCE_BUILD: "1"
  dependencies:
    - "check-updates/${FEDORA_VERSION}"
    - "build/${FEDORA_VERSION}"

# Ensure there are no existing layers on the builder. Existing layers when used
# as cache will retain their previous timestamp resulting in non-reproduible
# builds.
clean:
  tags:
    - podman
    - $ARCH
  stage: clean
  script:
    - podman image prune --all --force
  parallel:
    matrix:
      - ARCH:
        - "x86_64"
        - "aarch64"
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - when: manual
      allow_failure: true

check-updates-36:
  extends: .check-updates
  variables:
    FEDORA_VERSION: "36"
  parallel:
    matrix:
      - ARCH:
        - "x86_64"
        - "aarch64"

check-updates-37:
  extends: .check-updates
  variables:
    FEDORA_VERSION: "37"
  parallel:
    matrix:
      - ARCH:
        - "x86_64"
        - "aarch64"

build-36:
  extends: .build
  variables:
    FEDORA_VERSION: "36"
  parallel:
    matrix:
      - ARCH:
        - "x86_64"
        - "aarch64"
  dependencies:
    - check-updates-36

build-37:
  extends: .build
  variables:
    FEDORA_VERSION: "37"
  parallel:
    matrix:
      - ARCH:
        - "x86_64"
        - "aarch64"
  dependencies:
    - check-updates-37

make-manifest-list-36:
  extends: .make-manifest-list
  variables:
    FEDORA_VERSION: "36"
  dependencies:
    - check-updates-36
    - build-36

make-manifest-list-37:
  extends: .make-manifest-list
  variables:
    FEDORA_VERSION: "37"
  dependencies:
    - check-updates-37
    - build-37
